services:
  api.backend:
    container_name: api.backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "${BACKEND_API_PORT}:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      db.redis:
        condition: service_healthy
    networks:
      - e_commerce_store

  db.redis:
    image: redis:latest
    container_name: db.redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/db/redis:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - e_commerce_store

networks:
  e_commerce_store:
    driver: bridge